roles:
  - name: geerlingguy.pip
    version: 3.1.0
  - name: datadog.datadog
    version: 6.1.0
collections:
  - name: community.docker
    version: 4.5.2
  - name: ansible.posix
    version: 1.5.2
  
